# Generated by Django 5.1.7 on 2025-03-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woman',
            options={'ordering': ['-time_created']},
        ),
        migrations.AddField(
            model_name='woman',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='woman',
            index=models.Index(fields=['-time_created'], name='women_woman_time_cr_6f9d6c_idx'),
        ),
    ]
