# Generated by Django 5.1.7 on 2025-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_woman_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Draft'), (1, 'Is published')], default=0),
        ),
    ]
