# Generated by Django 5.1.7 on 2025-03-16 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_category_woman_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woman',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.category'),
        ),
    ]
