# Generated by Django 5.1.7 on 2025-03-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_husband_m_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='woman',
            options={'ordering': ['-time_created'], 'verbose_name_plural': 'women'},
        ),
    ]
