# Generated by Django 5.1.7 on 2025-03-25 16:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_alter_woman_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='woman',
            options={'ordering': ['-time_created'], 'verbose_name': 'Famous women', 'verbose_name_plural': 'Famous women'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='content',
            field=models.TextField(blank=True, verbose_name='Post Text'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wuman', to='women.husband', verbose_name='Husband'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Draft'), (True, 'Is published')], default=0, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Required at least 5 symbols'), django.core.validators.MaxLengthValidator(limit_value=100, message='Maximum is 100 symbols')], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='women.tagpost', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of Creation'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of Update'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
